repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key

  - repo: local
    hooks:
      - id: block-secrets
        name: Secrets Commit Blocker
        entry: bash scripts/pre-commit-git-hook/pre-commit-git-hook.sh
        language: system
        always_run: true
        pass_filenames: false
